version: '3.8'

services:
  # MySQL 数据库服务
  mysql:
    image: mysql:8.0
    container_name: property_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: property_management
      MYSQL_USER: property_user
      MYSQL_PASSWORD: property_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - property_network
    command: --default-authentication-plugin=mysql_native_password

  # 物业管理 API 服务
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: property_api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: property_user
      DB_PASSWORD: property_pass
      DB_NAME: property_management
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - property_network
    volumes:
      - ./logs:/app/logs

  # Nginx 反向代理 (可选)
  nginx:
    image: nginx:alpine
    container_name: property_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    networks:
      - property_network

volumes:
  mysql_data:
    driver: local

networks:
  property_network:
    driver: bridge
